import { describe, expect, it } from "vitest";

import { ConfigError } from "@pagedeck/core/exit";
import { ROUTING_VERSION } from "@pagedeck/core/routing";
import type { RoutingManifest } from "@pagedeck/core/routing";

import { ESCAPED } from "../../edge/src/conformance.test-support.js";
import { nginx } from "./index.js";

describe("nginx writes locations in the spelling nginx matches on", () => {
  function config(): string {
    const artifact = nginx().compile(ESCAPED).artifacts[0];
    return artifact === undefined ? "" : artifact.contents;
  }

  it("decodes every path it matches against, and nothing it sends back", () => {
    expect(config())
      .toBe(`# Generated by @pagedeck/edge from the routing document. Do not edit.
# Include inside the server block serving the default tree.

if ($uri = "/manifest.json") { return 404; }
if ($uri ~ "^/\\.pagedeck(/|$)") { return 404; }

location = "/en/café" { return 301 "/en/coffee"; }
location = "/en/café/" {
    add_header "X-Frame-Options" "DENY" always;
    return 301 "/en/coffee";
}
location = "/en/coffee/" { return 308 "/en/coffee"; }

location ^~ "/en/café/" {
    add_header "X-Frame-Options" "DENY" always;
}

error_page 404 "/en/404-café";
location = "/en/404-café" { internal; }
`);
  });
});

describe("nginx refuses an escape it cannot match on", () => {
  function withRedirectFrom(from: string): RoutingManifest {
    return {
      version: ROUTING_VERSION,
      site: { trailingSlash: "never" },
      trees: [
        {
          redirects: [
            { from, to: "/en/about", status: 301, source: "config", via: [] },
          ],
          headers: [],
        },
      ],
    };
  }

  it("refuses an escaped path separator, which it cannot tell from a real one", () => {
    expect(() =>
      nginx().compile(withRedirectFrom("/a%2Fb")),
    ).toThrow(
      new ConfigError(
        `Edge target "nginx": 1 value cannot be expressed by this target — remove the character, or compile a target that can express it:
  the default tree's redirect from "/a%2Fb" — nginx decodes the request URI before it selects a location, so an escaped "%2F" cannot be told apart from a real path separator`,
      ),
    );
  });

  it("refuses an escaped dollar sign, which decodes into an nginx variable", () => {
    expect(() =>
      nginx().compile(withRedirectFrom("/price%24")),
    ).toThrow(
      new ConfigError(
        `Edge target "nginx": 1 value cannot be expressed by this target — remove the character, or compile a target that can express it:
  the default tree's redirect from "/price%24" — nginx interpolates "$" inside a quoted string, and offers no escape for a literal one`,
      ),
    );
  });

  it("refuses an escape that is not valid UTF-8", () => {
    expect(() =>
      nginx().compile(withRedirectFrom("/a%FFb")),
    ).toThrow(
      new ConfigError(
        `Edge target "nginx": 1 value cannot be expressed by this target — remove the character, or compile a target that can express it:
  the default tree's redirect from "/a%FFb" — nginx decodes the request URI as bytes, and this path holds a percent-escape that is not valid UTF-8`,
      ),
    );
  });

  it("refuses an escaped control character", () => {
    expect(() =>
      nginx().compile(withRedirectFrom("/a%0Ab")),
    ).toThrow(
      new ConfigError(
        `Edge target "nginx": 1 value cannot be expressed by this target — remove the character, or compile a target that can express it:
  the default tree's redirect from "/a%0Ab" — nginx decodes the request URI before it selects a location, and the decoded path holds a control character no directive can carry`,
      ),
    );
  });
});
