import { describe, expect, it } from "vitest";

import type { EdgeArtifact } from "@pagedeck/edge";

import { FIXTURE } from "../../edge/src/fixture.test-support.js";
import { nginx } from "./index.js";

function defaultTree(): readonly EdgeArtifact[] {
  return nginx().compile(FIXTURE).artifacts.filter(
    (artifact) => artifact.domain === undefined,
  );
}

function contentsOf(path: string): string {
  const artifact = defaultTree().find((candidate) => candidate.path === path);
  if (artifact === undefined) throw new Error(`no ${path} for nginx`);
  return artifact.contents;
}

describe("nginx", () => {
  it("emits exact locations for redirects and prefix locations for headers, each carrying its set", () => {
    expect(contentsOf("routing.conf"))
      .toBe(`# Generated by @pagedeck/edge from the routing document. Do not edit.
# Include inside the server block serving the default tree.

if ($uri = "/manifest.json") { return 404; }
if ($uri ~ "^/\\.pagedeck(/|$)") { return 404; }

location = "/en/about/" {
    add_header "X-Content-Type-Options" "nosniff" always;
    add_header "Referrer-Policy" "strict-origin-when-cross-origin" always;
    return 308 "/en/about";
}
location = "/en/docs/intro/" {
    add_header "X-Frame-Options" "DENY" always;
    return 308 "/en/docs/intro";
}
location = "/en/legacy" {
    add_header "X-Content-Type-Options" "nosniff" always;
    add_header "Referrer-Policy" "strict-origin-when-cross-origin" always;
    return 301 "/en/about";
}
location = "/en/legacy/" {
    add_header "X-Content-Type-Options" "nosniff" always;
    add_header "Referrer-Policy" "strict-origin-when-cross-origin" always;
    return 301 "/en/about";
}
location = "/en/old-docs" {
    add_header "X-Content-Type-Options" "nosniff" always;
    add_header "Referrer-Policy" "strict-origin-when-cross-origin" always;
    return 308 "/en/docs/intro";
}
location = "/en/old-docs/" {
    add_header "X-Content-Type-Options" "nosniff" always;
    add_header "Referrer-Policy" "strict-origin-when-cross-origin" always;
    return 308 "/en/docs/intro";
}

location ^~ "/en/docs/" {
    add_header "X-Frame-Options" "DENY" always;
}

location ^~ "/en/" {
    add_header "X-Content-Type-Options" "nosniff" always;
    add_header "Referrer-Policy" "strict-origin-when-cross-origin" always;
}

error_page 404 "/en/404";
location = "/en/404" {
    internal;
    add_header "X-Content-Type-Options" "nosniff" always;
    add_header "Referrer-Policy" "strict-origin-when-cross-origin" always;
}
`);
  });
});
