import { describe, expect, it } from "vitest";

import type { EdgeArtifact } from "@pagedeck/edge";

import { FIXTURE } from "../../edge/src/fixture.test-support.js";
import { cloudfront } from "./index.js";

function defaultTree(): readonly EdgeArtifact[] {
  return cloudfront().compile(FIXTURE).artifacts.filter(
    (artifact) => artifact.domain === undefined,
  );
}

function contentsOf(path: string): string {
  const artifact = defaultTree().find((candidate) => candidate.path === path);
  if (artifact === undefined) throw new Error(`no ${path} for cloudfront-function`);
  return artifact.contents;
}

describe("cloudfront-function", () => {
  it("emits one viewer-request function holding the redirect table, each redirect carrying its set", () => {
    expect(contentsOf("routing.request.js"))
      .toBe(`// Generated by @pagedeck/edge from the routing document. Do not edit.
// CloudFront viewer-request function for the default tree.

var DEPLOY_MANIFEST = "/manifest.json";
var DEPLOY_DIRECTORY = "/.pagedeck";
var UNSERVED = "/.pagedeck/unserved";

function reservedKey(uri) {
  var path = uri;
  try {
    path = decodeURIComponent(uri);
  } catch (malformed) {
    path = uri;
  }
  var parts = path.split("/");
  var kept = [];
  for (var at = 0; at < parts.length; at++) {
    if (parts[at] === "" || parts[at] === ".") continue;
    if (parts[at] === "..") {
      kept.pop();
      continue;
    }
    kept.push(parts[at]);
  }
  var resolved = "/" + kept.join("/");
  return resolved === DEPLOY_MANIFEST ||
    resolved === DEPLOY_DIRECTORY ||
    resolved.indexOf(DEPLOY_DIRECTORY + "/") === 0;
}

var REDIRECTS = Object.freeze({
  "/en/about/": { to: "/en/about", status: 308, description: "Permanent Redirect" },
  "/en/docs/intro/": { to: "/en/docs/intro", status: 308, description: "Permanent Redirect" },
  "/en/legacy": { to: "/en/about", status: 301, description: "Moved Permanently" },
  "/en/legacy/": { to: "/en/about", status: 301, description: "Moved Permanently" },
  "/en/old-docs": { to: "/en/docs/intro", status: 308, description: "Permanent Redirect" },
  "/en/old-docs/": { to: "/en/docs/intro", status: 308, description: "Permanent Redirect" },
});

var HEADERS = Object.freeze([
  { prefix: "/en/docs/", set: [{ name: "x-frame-options", value: "DENY" }] },
  { prefix: "/en/", set: [{ name: "x-content-type-options", value: "nosniff" }, { name: "referrer-policy", value: "strict-origin-when-cross-origin" }] },
]);

function setHeaders(headers, uri) {
  for (var i = 0; i < HEADERS.length; i++) {
    if (uri.indexOf(HEADERS[i].prefix) !== 0) continue;
    for (var j = 0; j < HEADERS[i].set.length; j++) {
      Object.defineProperty(headers, HEADERS[i].set[j].name, { value: { value: HEADERS[i].set[j].value }, writable: true, enumerable: true, configurable: true });
    }
    break;
  }
  return headers;
}

function handler(event) {
  var request = event.request;
  if (reservedKey(request.uri)) request.uri = UNSERVED;
  var rule = Object.prototype.hasOwnProperty.call(REDIRECTS, request.uri)
    ? REDIRECTS[request.uri]
    : null;
  if (rule) {
    return {
      statusCode: rule.status,
      statusDescription: rule.description,
      headers: setHeaders({ location: { value: rule.to } }, request.uri),
    };
  }
  return request;
}
`);
  });

  it("emits one viewer-response function holding the first-match header table, the 404 page answered with its own set", () => {
    expect(contentsOf("routing.response.js"))
      .toBe(`// Generated by @pagedeck/edge from the routing document. Do not edit.
// CloudFront viewer-response function for the default tree.

var HEADERS = Object.freeze([
  { prefix: "/en/docs/", set: [{ name: "x-frame-options", value: "DENY" }] },
  { prefix: "/en/", set: [{ name: "x-content-type-options", value: "nosniff" }, { name: "referrer-policy", value: "strict-origin-when-cross-origin" }] },
]);

function setHeaders(headers, uri) {
  for (var i = 0; i < HEADERS.length; i++) {
    if (uri.indexOf(HEADERS[i].prefix) !== 0) continue;
    for (var j = 0; j < HEADERS[i].set.length; j++) {
      Object.defineProperty(headers, HEADERS[i].set[j].name, { value: { value: HEADERS[i].set[j].value }, writable: true, enumerable: true, configurable: true });
    }
    break;
  }
  return headers;
}

var NOT_FOUND = "/en/404";

function handler(event) {
  var request = event.request;
  var response = event.response;
  setHeaders(response.headers, response.statusCode === 404 ? NOT_FOUND : request.uri);
  return response;
}
`);
  });

  it("emits the 404 as distribution configuration, not as function code", () => {
    expect(contentsOf("error-responses.json")).toBe(`{
  "CustomErrorResponses": {
    "Quantity": 1,
    "Items": [
      {
        "ErrorCode": 404,
        "ResponsePagePath": "/en/404",
        "ResponseCode": "404",
        "ErrorCachingMinTTL": 0
      }
    ]
  }
}
`);
  });

  it("carries no sourcemap and no sourceMappingURL", () => {
    for (const artifact of cloudfront().compile(FIXTURE).artifacts) {
      expect(artifact.contents).not.toContain("sourceMappingURL");
    }
  });
});
