import {
  DEPLOY_DIRECTORY,
  DEPLOY_MANIFEST_PATH,
  variantPath,
} from "@pagedeck/core/routing";
import type { ResolvedExperiment, RoutingTree } from "@pagedeck/core/routing";

import type { EdgeArtifact, FunctionRuntime } from "./artifact.js";
import { UNSERVED_KEY } from "./reserved-keys.js";
import { jsLiteral } from "./encode.js";
import type { Fault } from "./faults.js";
import { treeOf } from "./faults.js";
import type { CompiledTree } from "./normalize.js";

export const CLOUDFRONT_FUNCTION_LIMIT = 10 * 1024;

/**
 * Measured over the import file, which is larger than what the store holds: the safe
 * direction, since an under-estimate fails at import after a green build.
 */
export const CLOUDFRONT_KVS_LIMIT = 5 * 1024 * 1024;

const DESCRIPTIONS = {
  301: "Moved Permanently",
  302: "Found",
  307: "Temporary Redirect",
  308: "Permanent Redirect",
} as const;

interface Stage {
  declarations: readonly string[];
  body: readonly string[];
  async: boolean;
}

function handler(stages: readonly Stage[], exit: string): string {
  const blocks = stages
    .map((stage) => stage.declarations.join("\n"))
    .filter((block) => block !== "");
  const body = stages.flatMap((stage) => stage.body);
  const keyword = stages.some((stage) => stage.async)
    ? "async function"
    : "function";
  return [
    ...(blocks.length === 0 ? [] : [blocks.join("\n\n")]),
    "",
    `${keyword} handler(event) {`,
    ...body.map((line) => `  ${line}`),
    `  return ${exit};`,
    "}",
    "",
  ].join("\n");
}

function banner(what: string, domain: string | undefined): string {
  return `// Generated by @pagedeck/edge from the routing document. Do not edit.\n// ${what} for ${treeOf(domain)}.`;
}

// `hasOwnProperty` is unneeded while every key starts `/`, and kept so nobody has to
// re-prove that.
function inlineRedirects(tree: CompiledTree): Stage {
  const rows = tree.redirects.map(
    (rule) =>
      `  ${jsLiteral(rule.from)}: { to: ${jsLiteral(rule.to)}, status: ${String(rule.status)}, description: ${jsLiteral(DESCRIPTIONS[rule.status])} },`,
  );
  return {
    async: false,
    declarations: [
      `var REDIRECTS = Object.freeze({`,
      ...rows,
      `});`,
      ...redirectHeaders(tree),
    ],
    body: [
      "var rule = Object.prototype.hasOwnProperty.call(REDIRECTS, request.uri)",
      "  ? REDIRECTS[request.uri]",
      "  : null;",
      ...respond(tree.headers.length > 0),
    ],
  };
}

// `get` throws on a missing key, the ordinary case, so the miss is caught.
function datasetRedirects(tree: CompiledTree): Stage {
  return {
    async: true,
    declarations: [
      `import cf from "cloudfront";`,
      ``,
      `var STORE = cf.kvs();`,
      ...redirectHeaders(tree),
    ],
    body: [
      "var packed = null;",
      "try {",
      '  packed = await STORE.get(request.uri, { format: "string" });',
      "} catch (miss) {",
      "  packed = null;",
      "}",
      "var rule = packed === null ? null : JSON.parse(packed);",
      ...respond(tree.headers.length > 0),
    ],
  };
}

// A rewrite, not a response, so the origin miss serves the 404 page with its headers (#556).
// Matched on the decoded, dot-resolved path S3 reads, not on the URI as sent.
function reservedKeyStage(): Stage {
  return {
    async: false,
    declarations: [
      `var DEPLOY_MANIFEST = ${jsLiteral(DEPLOY_MANIFEST_PATH)};`,
      `var DEPLOY_DIRECTORY = ${jsLiteral(DEPLOY_DIRECTORY)};`,
      `var UNSERVED = ${jsLiteral(UNSERVED_KEY)};`,
      "",
      "function reservedKey(uri) {",
      "  var path = uri;",
      "  try {",
      "    path = decodeURIComponent(uri);",
      "  } catch (malformed) {",
      "    path = uri;",
      "  }",
      '  var parts = path.split("/");',
      "  var kept = [];",
      "  for (var at = 0; at < parts.length; at++) {",
      '    if (parts[at] === "" || parts[at] === ".") continue;',
      '    if (parts[at] === "..") {',
      "      kept.pop();",
      "      continue;",
      "    }",
      "    kept.push(parts[at]);",
      "  }",
      '  var resolved = "/" + kept.join("/");',
      "  return resolved === DEPLOY_MANIFEST ||",
      "    resolved === DEPLOY_DIRECTORY ||",
      '    resolved.indexOf(DEPLOY_DIRECTORY + "/") === 0;',
      "}",
    ],
    body: ["if (reservedKey(request.uri)) request.uri = UNSERVED;"],
  };
}

// Writes the headers itself: whether CloudFront runs the viewer-response function over a
// generated response is unverified (#559).
function respond(withHeaders: boolean): readonly string[] {
  const location = "{ location: { value: rule.to } }";
  return [
    "if (rule) {",
    "  return {",
    "    statusCode: rule.status,",
    "    statusDescription: rule.description,",
    withHeaders
      ? `    headers: setHeaders(${location}, request.uri),`
      : `    headers: ${location},`,
    "  };",
    "}",
  ];
}

const DATASET_PATH = "routing.kvs.json";

function dataset(tree: CompiledTree): string {
  return `${JSON.stringify(
    {
      data: tree.redirects.map((rule) => ({
        key: rule.from,
        value: JSON.stringify({
          to: rule.to,
          status: rule.status,
          description: DESCRIPTIONS[rule.status],
        }),
      })),
    },
    null,
    2,
  )}\n`;
}

const ARN_PLACEHOLDER = "${PAGEDECK_ROUTING_KVS_ARN}";

function functionConfig(
  tree: CompiledTree,
  runtime: FunctionRuntime,
  importPath: string,
): string {
  return `${JSON.stringify(
    {
      Comment: `Routing for ${treeOf(tree.domain)} (@pagedeck/edge). Import "${importPath}" into the KeyValueStore below before publishing this function.`,
      Runtime: runtime,
      KeyValueStoreAssociations: {
        Quantity: 1,
        Items: [{ KeyValueStoreARN: ARN_PLACEHOLDER }],
      },
    },
    null,
    2,
  )}\n`;
}

// `defineProperty`, not assignment: `headers["__proto__"] = …` sets the prototype (#317), and
// CloudFront sends only enumerable fields. AWS documents it in both runtimes; `node:vm` cannot.
function headerTable(tree: RoutingTree): readonly string[] {
  const rows = tree.headers.map((rule) => {
    const fields = rule.set
      .map(
        (field) =>
          `{ name: ${jsLiteral(field.name.toLowerCase())}, value: ${jsLiteral(field.value)} }`,
      )
      .join(", ");
    return `  { prefix: ${jsLiteral(rule.prefix)}, set: [${fields}] },`;
  });
  return [
    `var HEADERS = Object.freeze([`,
    ...rows,
    `]);`,
    "",
    "function setHeaders(headers, uri) {",
    "  for (var i = 0; i < HEADERS.length; i++) {",
    "    if (uri.indexOf(HEADERS[i].prefix) !== 0) continue;",
    "    for (var j = 0; j < HEADERS[i].set.length; j++) {",
    "      Object.defineProperty(headers, HEADERS[i].set[j].name, { value: { value: HEADERS[i].set[j].value }, writable: true, enumerable: true, configurable: true });",
    "    }",
    "    break;",
    "  }",
    "  return headers;",
    "}",
  ];
}

function redirectHeaders(tree: RoutingTree): readonly string[] {
  return tree.headers.length === 0 ? [] : ["", ...headerTable(tree)];
}

// A 404 takes the 404 page's own set whatever was asked for (#559): `request.uri` is the
// viewer's path, never `ResponsePagePath`.
function headerStage(tree: RoutingTree): Stage {
  return {
    async: false,
    declarations: [
      ...headerTable(tree),
      ...(tree.notFound === undefined
        ? []
        : ["", `var NOT_FOUND = ${jsLiteral(tree.notFound)};`]),
    ],
    body: [
      tree.notFound === undefined
        ? "setHeaders(response.headers, request.uri);"
        : "setHeaders(response.headers, response.statusCode === 404 ? NOT_FOUND : request.uri);",
    ],
  };
}

// Not `HttpOnly`: the site's own analytics must read the arm (#35). `Lax`, so a visitor
// arriving from a search result keeps their arm.
const COOKIE_ATTRIBUTES = "Path=/; Max-Age=7776000; Secure; SameSite=Lax";

// Arms are an array walked by name: a cookie value as an object key could answer an
// `Object.prototype` member such as `__proto__`.
function splitTable(
  splits: readonly ResolvedExperiment[],
  keying: "primary" | "primary-and-arms",
): readonly string[] {
  // Named by index in core's sorted array, so the source depends only on the document.
  const named = (index: number): string => `SPLIT_${String(index)}`;
  const entries = splits.map((split, index) => {
    const total = split.variants.reduce(
      (sum, variant) => sum + variant.weight,
      0,
    );
    const arms = split.variants
      .map(
        (variant) =>
          `{ name: ${jsLiteral(variant.name)}, weight: ${String(variant.weight)}, to: ${jsLiteral(variantPath(variant.name, split.path))} }`,
      )
      .join(", ");
    return `var ${named(index)} = Object.freeze({ cookie: ${jsLiteral(split.cookie)}, total: ${String(total)}, arms: [${arms}] });`;
  });
  const rows = splits.flatMap((split, index) => {
    const keys =
      keying === "primary"
        ? [split.path]
        : [
            split.path,
            ...split.variants.map((variant) =>
              variantPath(variant.name, split.path),
            ),
          ];
    return keys.map((key) => `  ${jsLiteral(key)}: ${named(index)},`);
  });
  return [...entries, "", `var SPLITS = Object.freeze({`, ...rows, `});`];
}

// Recomputed in both functions from `context.requestId`, since nothing passes between them.
// The lines after the djb2 loop spread its top bits; runtime 1.0 has no `Math.imul`.
const ARM_FOR: readonly string[] = [
  "function armFor(split, request, requestId) {",
  "  var carried = request.cookies || {};",
  "  var held = Object.prototype.hasOwnProperty.call(carried, split.cookie)",
  "    ? carried[split.cookie].value",
  "    : null;",
  "  for (var kept = 0; kept < split.arms.length; kept++) {",
  "    if (split.arms[kept].name === held) {",
  "      return { arm: split.arms[kept], held: true };",
  "    }",
  "  }",
  '  var seed = requestId + "|" + split.cookie;',
  "  var hash = 5381;",
  "  for (var at = 0; at < seed.length; at++) {",
  "    hash = (((hash << 5) + hash) ^ seed.charCodeAt(at)) >>> 0;",
  "  }",
  "  hash = (hash ^ (hash >>> 15)) >>> 0;",
  "  hash = (hash + ((hash << 3) >>> 0)) >>> 0;",
  "  hash = (hash ^ (hash >>> 11)) >>> 0;",
  "  hash = (hash + ((hash << 15) >>> 0)) >>> 0;",
  "  var roll = (hash / 4294967296) * split.total;",
  "  var seen = 0;",
  "  var chosen = split.arms[split.arms.length - 1];",
  "  for (var walk = 0; walk < split.arms.length; walk++) {",
  "    seen += split.arms[walk].weight;",
  "    if (roll < seen) {",
  "      chosen = split.arms[walk];",
  "      break;",
  "    }",
  "  }",
  "  return { arm: chosen, held: false };",
  "}",
];

// Rewritten on the first request, not deferred: deferring biases every arm toward returning
// visitors (#35).
function rewriteStage(splits: readonly ResolvedExperiment[]): Stage {
  return {
    async: false,
    declarations: [...splitTable(splits, "primary"), "", ...ARM_FOR],
    body: [
      "var split = Object.prototype.hasOwnProperty.call(SPLITS, request.uri)",
      "  ? SPLITS[request.uri]",
      "  : null;",
      "if (split) {",
      "  request.uri = armFor(split, request, event.context.requestId).arm.to;",
      "}",
    ],
  };
}

// `response.cookies`, not a `set-cookie` header: on this API `Set-Cookie` is not in `headers`.
// The table is keyed by every arm's `to` too, in case this is handed the rewritten URI.
function assignStage(splits: readonly ResolvedExperiment[]): Stage {
  return {
    async: false,
    declarations: [
      ...splitTable(splits, "primary-and-arms"),
      "",
      `var COOKIE_ATTRIBUTES = ${jsLiteral(COOKIE_ATTRIBUTES)};`,
      "",
      ...ARM_FOR,
    ],
    body: [
      "var split = Object.prototype.hasOwnProperty.call(SPLITS, request.uri)",
      "  ? SPLITS[request.uri]",
      "  : null;",
      "if (split) {",
      "  var assigned = armFor(split, request, event.context.requestId);",
      "  if (!assigned.held) {",
      "    if (!response.cookies) response.cookies = {};",
      "    response.cookies[split.cookie] = {",
      "      value: assigned.arm.name,",
      "      attributes: COOKIE_ATTRIBUTES,",
      "    };",
      "  }",
      "}",
    ],
  };
}

function errorResponses(notFound: string): string {
  return `${JSON.stringify(
    {
      CustomErrorResponses: {
        Quantity: 1,
        Items: [
          {
            ErrorCode: 404,
            ResponsePagePath: notFound,
            ResponseCode: "404",
            ErrorCachingMinTTL: 0,
          },
        ],
      },
    },
    null,
    2,
  )}\n`;
}

export function compileCloudFront(
  tree: CompiledTree,
  limit: number | undefined,
  _faults: Fault[],
): readonly EdgeArtifact[] {
  const artifacts: EdgeArtifact[] = [];
  const splits = tree.experiments ?? [];

  // Redirects before the rewrite, so only an address the viewer typed meets the redirect
  // table, never a minted `/_v/` path (#35).
  const request = (redirect: Stage | undefined): string =>
    handler(
      [
        {
          async: false,
          declarations: [
            banner("CloudFront viewer-request function", tree.domain),
          ],
          body: ["var request = event.request;"],
        },
        reservedKeyStage(),
        ...(redirect === undefined ? [] : [redirect]),
        ...(splits.length === 0 ? [] : [rewriteStage(splits)]),
      ],
      "request",
    );
  const hasRedirects = tree.redirects.length > 0;
  const inlineForm = request(hasRedirects ? inlineRedirects(tree) : undefined);
  const datasetForm = request(
    hasRedirects ? datasetRedirects(tree) : undefined,
  );
  // `hasRedirects` first: with no table to move out, the dataset form would publish an empty
  // store.
  const fits =
    !hasRedirects ||
    limit === undefined ||
    Buffer.byteLength(inlineForm, "utf8") <= limit;
  artifacts.push({
    ...(tree.domain === undefined ? {} : { domain: tree.domain }),
    role: "function",
    slot: "viewer-request",
    // The dataset form's `import` and `await` are 2.0-only.
    runtime: fits ? "cloudfront-js-1.0" : "cloudfront-js-2.0",
    path: "routing.request.js",
    contents: fits ? inlineForm : datasetForm,
  });
  if (!fits) {
    artifacts.push({
      ...(tree.domain === undefined ? {} : { domain: tree.domain }),
      role: "function-config",
      path: "routing.request.config.json",
      contents: functionConfig(tree, "cloudfront-js-2.0", DATASET_PATH),
    });
    artifacts.push({
      ...(tree.domain === undefined ? {} : { domain: tree.domain }),
      role: "dataset",
      path: DATASET_PATH,
      contents: dataset(tree),
    });
  }

  if (tree.headers.length > 0 || splits.length > 0) {
    artifacts.push({
      ...(tree.domain === undefined ? {} : { domain: tree.domain }),
      role: "function",
      slot: "viewer-response",
      runtime: "cloudfront-js-1.0",
      path: "routing.response.js",
      contents: handler(
        [
          {
            async: false,
            declarations: [
              banner("CloudFront viewer-response function", tree.domain),
            ],
            body: [
              "var request = event.request;",
              "var response = event.response;",
            ],
          },
          ...(tree.headers.length === 0 ? [] : [headerStage(tree)]),
          ...(splits.length === 0 ? [] : [assignStage(splits)]),
        ],
        "response",
      ),
    });
  }

  if (tree.notFound !== undefined) {
    artifacts.push({
      ...(tree.domain === undefined ? {} : { domain: tree.domain }),
      role: "distribution-config",
      path: "error-responses.json",
      contents: errorResponses(tree.notFound),
    });
  }

  return artifacts;
}
