import { describe, expect, it } from "vitest";

import { ConfigError } from "@pagedeck/core/exit";
import { ROUTING_VERSION } from "@pagedeck/core/routing";
import type { RoutingManifest } from "@pagedeck/core/routing";

import { compileRouting } from "./index.js";
import {
  comparable,
  interpretCloudFront,
  interpretNetlify,
  interpretNginx,
  interpretWorker,
} from "./interpret.test-support.js";
import { resolveRequest } from "./oracle.test-support.js";
import type { EdgeRequest } from "./oracle.test-support.js";

const ESCAPED: RoutingManifest = {
  version: ROUTING_VERSION,
  site: { trailingSlash: "never" },
  trees: [
    {
      redirects: [
        {
          from: "/en/caf%C3%A9",
          to: "/en/coffee",
          status: 301,
          source: "config",
          via: [],
        },
      ],
      notFound: "/en/404-caf%C3%A9",
      headers: [
        {
          prefix: "/en/caf%C3%A9/",
          set: [{ name: "X-Frame-Options", value: "DENY" }],
        },
      ],
    },
  ],
};

const REQUESTS: readonly (EdgeRequest & { what: string })[] = [
  { what: "an escaped redirect source", path: "/en/caf%C3%A9", found: false },
  {
    what: "a page under an escaped header prefix",
    path: "/en/caf%C3%A9/menu",
    found: true,
  },
  { what: "a miss served by an escaped 404 page", path: "/gone", found: false },
];

describe("an escaped path answers the same on every target", () => {
  for (const request of REQUESTS) {
    it(`cloudfront-function answers ${request.what}`, async () => {
      const { artifacts } = compileRouting(ESCAPED, {
        target: "cloudfront-function",
      });
      expect(comparable(await interpretCloudFront(artifacts, request))).toEqual(
        comparable(resolveRequest(ESCAPED, request)),
      );
    });

    it(`netlify answers ${request.what}`, () => {
      const { artifacts } = compileRouting(ESCAPED, { target: "netlify" });
      expect(comparable(interpretNetlify(artifacts, request))).toEqual(
        comparable(resolveRequest(ESCAPED, request)),
      );
    });

    it(`nginx answers ${request.what}`, () => {
      const { artifacts } = compileRouting(ESCAPED, { target: "nginx" });
      expect(comparable(interpretNginx(artifacts, request))).toEqual(
        comparable(resolveRequest(ESCAPED, request)),
      );
    });

    it(`cloudflare-worker answers ${request.what}`, async () => {
      const { artifacts } = compileRouting(ESCAPED, {
        target: "cloudflare-worker",
      });
      expect(comparable(await interpretWorker(artifacts, request))).toEqual(
        comparable(resolveRequest(ESCAPED, request)),
      );
    });
  }
});

describe("nginx writes locations in the spelling nginx matches on", () => {
  function config(): string {
    const artifact = compileRouting(ESCAPED, { target: "nginx" }).artifacts[0];
    return artifact === undefined ? "" : artifact.contents;
  }

  it("decodes every path it matches against, and nothing it sends back", () => {
    expect(config())
      .toBe(`# Generated by @pagedeck/edge from the routing document. Do not edit.
# Include inside the server block serving the default tree.

if ($uri = "/manifest.json") { return 404; }
if ($uri ~ "^/\\.pagedeck(/|$)") { return 404; }

location = "/en/café" { return 301 "/en/coffee"; }
location = "/en/café/" {
    add_header "X-Frame-Options" "DENY" always;
    return 301 "/en/coffee";
}
location = "/en/coffee/" { return 308 "/en/coffee"; }

location ^~ "/en/café/" {
    add_header "X-Frame-Options" "DENY" always;
}

error_page 404 "/en/404-café";
location = "/en/404-café" { internal; }
`);
  });
});

describe("nginx refuses an escape it cannot match on", () => {
  function withRedirectFrom(from: string): RoutingManifest {
    return {
      version: ROUTING_VERSION,
      site: { trailingSlash: "never" },
      trees: [
        {
          redirects: [
            { from, to: "/en/about", status: 301, source: "config", via: [] },
          ],
          headers: [],
        },
      ],
    };
  }

  it("refuses an escaped path separator, which it cannot tell from a real one", () => {
    expect(() =>
      compileRouting(withRedirectFrom("/a%2Fb"), { target: "nginx" }),
    ).toThrow(
      new ConfigError(
        `Edge target "nginx": 1 value cannot be expressed by this target — remove the character, or compile a target that can express it:
  the default tree's redirect from "/a%2Fb" — nginx decodes the request URI before it selects a location, so an escaped "%2F" cannot be told apart from a real path separator`,
      ),
    );
  });

  it("refuses an escaped dollar sign, which decodes into an nginx variable", () => {
    expect(() =>
      compileRouting(withRedirectFrom("/price%24"), { target: "nginx" }),
    ).toThrow(
      new ConfigError(
        `Edge target "nginx": 1 value cannot be expressed by this target — remove the character, or compile a target that can express it:
  the default tree's redirect from "/price%24" — nginx interpolates "$" inside a quoted string, and offers no escape for a literal one`,
      ),
    );
  });

  it("refuses an escape that is not valid UTF-8", () => {
    expect(() =>
      compileRouting(withRedirectFrom("/a%FFb"), { target: "nginx" }),
    ).toThrow(
      new ConfigError(
        `Edge target "nginx": 1 value cannot be expressed by this target — remove the character, or compile a target that can express it:
  the default tree's redirect from "/a%FFb" — nginx decodes the request URI as bytes, and this path holds a percent-escape that is not valid UTF-8`,
      ),
    );
  });

  it("refuses an escaped control character", () => {
    expect(() =>
      compileRouting(withRedirectFrom("/a%0Ab"), { target: "nginx" }),
    ).toThrow(
      new ConfigError(
        `Edge target "nginx": 1 value cannot be expressed by this target — remove the character, or compile a target that can express it:
  the default tree's redirect from "/a%0Ab" — nginx decodes the request URI before it selects a location, and the decoded path holds a control character no directive can carry`,
      ),
    );
  });
});
