import { describe, expect, it } from "vitest";

import type { EdgeArtifact } from "@pagedeck/edge";

import { FIXTURE } from "../../edge/src/fixture.test-support.js";
import { cloudflareWorker } from "./index.js";

function defaultTree(): readonly EdgeArtifact[] {
  return cloudflareWorker().compile(FIXTURE).artifacts.filter(
    (artifact) => artifact.domain === undefined,
  );
}

function contentsOf(path: string): string {
  const artifact = defaultTree().find((candidate) => candidate.path === path);
  if (artifact === undefined) throw new Error(`no ${path} for cloudflare-worker`);
  return artifact.contents;
}

describe("cloudflare-worker", () => {
  it("emits one Worker module holding the redirect table, the header table and the 404 page", () => {
    expect(contentsOf("worker.js")).toBe(`// Generated by @pagedeck/edge from the routing document. Do not edit.
// Cloudflare Worker for the default tree. Bind the R2 bucket the deploy writes to as PAGEDECK_ORIGIN.

var ORIGIN = "PAGEDECK_ORIGIN";
var DOMAIN = null;
var KEY_PREFIX = "";
var DEPLOY_MANIFEST = "/manifest.json";
var DEPLOY_DIRECTORY = "/.pagedeck";
var NOT_FOUND = "/en/404";
var NOT_FOUND_KEY = "en/404/index.html";
var MANIFEST_TTL_MS = 10000;

var REDIRECTS = new Map([
  ["/en/about/", { to: "/en/about", status: 308 }],
  ["/en/docs/intro/", { to: "/en/docs/intro", status: 308 }],
  ["/en/legacy", { to: "/en/about", status: 301 }],
  ["/en/legacy/", { to: "/en/about", status: 301 }],
  ["/en/old-docs", { to: "/en/docs/intro", status: 308 }],
  ["/en/old-docs/", { to: "/en/docs/intro", status: 308 }],
]);

var HEADERS = [
  { prefix: "/en/docs/", set: [{ name: "X-Frame-Options", value: "DENY" }] },
  { prefix: "/en/", set: [{ name: "X-Content-Type-Options", value: "nosniff" }, { name: "Referrer-Policy", value: "strict-origin-when-cross-origin" }] },
];

function headersFor(path, headers) {
  for (var i = 0; i < HEADERS.length; i++) {
    if (path.indexOf(HEADERS[i].prefix) !== 0) continue;
    for (var j = 0; j < HEADERS[i].set.length; j++) {
      headers.set(HEADERS[i].set[j].name, HEADERS[i].set[j].value);
    }
    break;
  }
  return headers;
}

function requestPath(url) {
  var start = url.indexOf("/", url.indexOf("//") + 2);
  if (start === -1) return "/";
  var end = url.indexOf("?", start);
  return end === -1 ? url.slice(start) : url.slice(start, end);
}

function decoded(path) {
  if (/%2f|%5c|\\\\/i.test(path)) return null;
  var text;
  try {
    text = decodeURIComponent(path);
  } catch (malformed) {
    return null;
  }
  if (/[\\u0000-\\u001f\\u007f]/.test(text)) return null;
  var parts = text.split("/");
  for (var at = 0; at < parts.length; at++) {
    if (parts[at] === "." || parts[at] === "..") return null;
  }
  return text;
}

function reserved(text) {
  var bare = "/" + text.split("/").filter(function (part) { return part !== ""; }).join("/");
  return bare === DEPLOY_MANIFEST ||
    bare === DEPLOY_DIRECTORY ||
    bare.indexOf(DEPLOY_DIRECTORY + "/") === 0;
}

function namedPaths(text) {
  var manifest;
  try {
    manifest = JSON.parse(text);
  } catch (malformed) {
    return "it is not JSON (" + String(malformed.message).replace(/"[\\s\\S]*"/, "\\"\\u2026\\"") + ")";
  }
  var files = manifest !== null && typeof manifest === "object" ? manifest.files : undefined;
  if (!Array.isArray(files)) return "it has no files list";
  var paths = new Set();
  var bad = [];
  for (var at = 0; at < files.length; at++) {
    var row = files[at];
    if (row === null || typeof row !== "object" || typeof row.path !== "string") {
      bad.push("files[" + at + "]");
      continue;
    }
    var domain = row.domain === undefined ? null : row.domain;
    if (domain === DOMAIN) paths.add(row.path);
  }
  if (bad.length === 1) return bad[0] + " has no path";
  if (bad.length > 1) return bad.slice(0, -1).join(", ") + " and " + bad[bad.length - 1] + " have no path";
  return paths;
}

function kept(load) {
  var entry = null;
  return function (origin) {
    var now = Date.now();
    if (entry === null || now >= entry.until) {
      var next = { until: now + MANIFEST_TTL_MS, value: null };
      next.value = load(origin).catch(function (failure) {
        if (entry === next) entry = null;
        throw failure;
      });
      entry = next;
    }
    return entry.value;
  };
}

var live = kept(async function (origin) {
  var site = { paths: new Set(), broken: false, notFound: null };
  var object = await origin.get(DEPLOY_MANIFEST.slice(1));
  if (object !== null) {
    var named = namedPaths(await object.text());
    if (typeof named === "string") {
      site.broken = true;
      console.error("pagedeck Worker: manifest.json in the bucket bound as " + ORIGIN + " is not a deploy manifest: " + named + ", so every request but a refused one is answered 503 until it is read again " + MANIFEST_TTL_MS / 1000 + " s after this read \\u2014 deploy again to put a valid one");
    } else {
      site.paths = named;
    }
  }
  return site;
});

async function stored(page) {
  if (page === null) return null;
  var headers = new Headers();
  page.writeHttpMetadata(headers);
  return { body: await page.arrayBuffer(), headers: headers };
}

var refusalPage = kept(async function (origin) {
  return NOT_FOUND_KEY === null ? null : await stored(await origin.get(NOT_FOUND_KEY));
});

async function read(origin, paths, path) {
  var keys = path.endsWith("/") ? [path + "index.html"] : [path, path + "/index.html"];
  for (var at = 0; at < keys.length; at++) {
    if (paths.has(keys[at])) return await origin.get((KEY_PREFIX + keys[at]).slice(1));
  }
  return null;
}

var MONTHS = "JanFebMarAprMayJunJulAugSepOctNovDec";
var IMF_FIXDATE = /^(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun), (\\d\\d) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (\\d{4}) (\\d\\d):(\\d\\d):(\\d\\d) GMT$/;
var RFC850_DATE = /^(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday), (\\d\\d)-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-(\\d\\d) (\\d\\d):(\\d\\d):(\\d\\d) GMT$/;
var ASCTIME_DATE = /^(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) ([ \\d]\\d) (\\d\\d):(\\d\\d):(\\d\\d) (\\d{4})$/;

function utc(year, month, day, hour, minute, second) {
  return Date.UTC(year, MONTHS.indexOf(month) / 3, Number(day), Number(hour), Number(minute), Number(second));
}

function rfc850Year(digits) {
  var now = new Date().getUTCFullYear();
  var year = now - (now % 100) + Number(digits);
  return year > now + 50 ? year - 100 : year;
}

function httpDate(text) {
  var parts;
  if (text === null) return NaN;
  if ((parts = IMF_FIXDATE.exec(text)) !== null) return utc(Number(parts[3]), parts[2], parts[1], parts[4], parts[5], parts[6]);
  if ((parts = RFC850_DATE.exec(text)) !== null) return utc(rfc850Year(parts[3]), parts[2], parts[1], parts[4], parts[5], parts[6]);
  if ((parts = ASCTIME_DATE.exec(text)) !== null) return utc(Number(parts[6]), parts[1], parts[2], parts[3], parts[4], parts[5]);
  return NaN;
}

function unchanged(request, object) {
  var tags = request.headers.get("if-none-match");
  if (tags !== null) {
    if (tags.trim() === "*") return true;
    var own = object.httpEtag.replace(/^W\\//, "");
    var listed = tags.match(/(?:W\\/)?"[^"]*"/g) || [];
    for (var at = 0; at < listed.length; at++) {
      if (listed[at].replace(/^W\\//, "") === own) return true;
    }
    return false;
  }
  var since = httpDate(request.headers.get("if-modified-since"));
  return !isNaN(since) && Math.floor(object.uploaded.getTime() / 1000) * 1000 <= since;
}

function serve(request, object, path) {
  var headers = new Headers();
  object.writeHttpMetadata(headers);
  headersFor(path, headers);
  headers.set("etag", object.httpEtag);
  if (unchanged(request, object)) return new Response(null, { status: 304, headers: headers });
  return new Response(request.method === "HEAD" ? null : object.body, { status: 200, headers: headers });
}

function notFoundPage(origin, site) {
  if (site.notFound === null) {
    site.notFound = (async function () {
      return NOT_FOUND === null ? null : await stored(await read(origin, site.paths, NOT_FOUND));
    })().catch(function (failure) {
      site.notFound = null;
      throw failure;
    });
  }
  return site.notFound;
}

function missing(request, page, path) {
  if (page !== null) {
    return new Response(request.method === "HEAD" ? null : page.body.slice(0), { status: 404, headers: headersFor(NOT_FOUND, new Headers(page.headers)) });
  }
  return new Response(request.method === "HEAD" ? null : "Not Found", { status: 404, headers: headersFor(path, new Headers()) });
}

function unavailable(request, path) {
  return new Response(request.method === "HEAD" ? null : "Service Unavailable", { status: 503, headers: headersFor(path, new Headers()) });
}

export default {
  async fetch(request, env) {
    var origin = env[ORIGIN];
    var path = requestPath(request.url);
    if (request.method !== "GET" && request.method !== "HEAD") {
      var refused = headersFor(path, new Headers());
      refused.set("allow", "GET, HEAD");
      return new Response(null, { status: 405, headers: refused });
    }
    var text = decoded(path);
    if (text === null || reserved(text)) return missing(request, await refusalPage(origin), path);
    var rule = REDIRECTS.get(path);
    if (rule !== undefined) {
      var headers = headersFor(path, new Headers());
      headers.set("location", rule.to);
      return new Response(null, { status: rule.status, headers: headers });
    }
    var site = await live(origin);
    if (site.broken) return unavailable(request, path);
    var object = await read(origin, site.paths, path);
    if (object === null) return missing(request, await notFoundPage(origin, site), path);
    return serve(request, object, path);
  },
};
`);
  });

  it("emits nothing but the Worker, and no sourceMappingURL", () => {
    const artifacts = cloudflareWorker().compile(FIXTURE)
      .artifacts;
    expect(
      artifacts.map(
        (one) =>
          `${one.domain ?? "(default)"} ${one.role} ${one.path} binds ${String(one.binding)}`,
      ),
    ).toEqual([
      "(default) edge-module worker.js binds PAGEDECK_ORIGIN",
      "shop.example edge-module worker.js binds PAGEDECK_ORIGIN",
    ]);
    for (const artifact of artifacts) {
      expect(artifact.contents).not.toContain("sourceMappingURL");
    }
  });
});
